### ISSUE TITLE
使用SVN 配置 启动不了  直接报错啊

### ISSUE THREAD

**Issue by atliwen** [wesker0918/springCloud#1]
cloud:
    config:
      server:
        svn:
          uri: svn://***/edi/edithothparent/config-repo
          username: **
          password: ***1122
      enabled: true
  profiles:
    active: subversion

错误
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'environmentRepository' defined in org.springframework.cloud.config.server.config.Enviro
nmentRepositoryConfiguration$SvnRepositoryConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException
: Failed to instantiate [org.springframework.cloud.config.server.environment.SvnKitEnvironmentRepository]: Factory method 'environmentRepository' threw exception; nested excep
tion is java.lang.NoClassDefFoundError: org/tmatesoft/svn/core/SVNException

楼主有解决的办法吗

**Comment by wesker0918** [comment]
需要在pom.xml中添加
`<dependency>
			<groupId>org.tmatesoft.svnkit</groupId>
			<artifactId>svnkit</artifactId>
		</dependency>`

**Comment by atliwen** [comment]
谢谢 解惑 ！！！
